name: bigquery-dataflow
project_id: gemini-power-test
region: europe-west2
service_manager_spec:
    name: servicedirector-bq-flow
    service_account: servicedirector-sa
    deployment:
        source_path: .
        buildable_module_path: cmd/bq-servicedirector
        image: europe-west2-docker.pkg.dev/gemini-power-test/cloud-deploy/servicedirector-bq-flow:da4e32e7
        image_repo: cloud-deploy
        service_url: ""
        region: europe-west2
        platform: ""
        cpu: "1"
        memory: 512Mi
        environment_vars:
            DATAFLOW_NAME: conductor
            PROJECT_ID: gemini-power-test
            SERVICE_NAME: servicedirector-bq-flow
    command_topic:
        name: command-topic
        lookup:
            key: command-subscription-id
            method: yaml
    completion_topic:
        name: completion-topic
        lookup:
            key: completion-topic-id
            method: yaml
dataflows:
    bigquery-flow:
        services:
            bigquery-service:
                name: bigquery-service
                service_account: bigquery-sa
                deployment:
                    source_path: .
                    buildable_module_path: cmd/bigquery
                    image: europe-west2-docker.pkg.dev/gemini-power-test/cloud-deploy/bigquery-service:94680e0b
                    image_repo: cloud-deploy
                    service_url: ""
                    region: europe-west2
                    platform: ""
                    cpu: "1"
                    memory: 512Mi
                    environment_vars:
                        DATAFLOW_NAME: bigquery-flow
                        PROJECT_ID: gemini-power-test
                        SERVICE_NAME: bigquery-service
                dependencies:
                    - servicedirector-bq-flow
            ingestion-service:
                name: ingestion-service
                service_account: ingestion-sa
                deployment:
                    source_path: .
                    buildable_module_path: cmd/ingestion
                    image: europe-west2-docker.pkg.dev/gemini-power-test/cloud-deploy/ingestion-service:15872712
                    image_repo: cloud-deploy
                    service_url: ""
                    region: europe-west2
                    platform: ""
                    cpu: "1"
                    memory: 512Mi
                    environment_vars:
                        DATAFLOW_NAME: bigquery-flow
                        MQTT_BROKER_URL: tcp://10.154.0.5:1883
                        MQTT_CLIENT_ID: test-client-devflow
                        MQTT_TOPIC: devices/+/data
                        MQTT_USERNAME: sreceiver
                        PROJECT_ID: gemini-power-test
                        SERVICE_NAME: ingestion-service
                    secret_environment_vars:
                        - name: MQTT_PASSWORD
                          value_from: SERVICE_PASS
                dependencies:
                    - servicedirector-bq-flow
        resources:
            topics:
                - name: ingestion-bq
                  producer_service:
                    name: ingestion-service
            subscriptions:
                - name: bq-ingestion
                  topic: ingestion-bq
                  consumer_service:
                    name: bigquery-service
            bigquery_datasets:
                - name: iot_data_bq
            bigquery_tables:
                - name: ingested_payloads_bq
                  producers:
                    - name: bigquery-service
                  dataset: iot_data_bq
                  schema_type: github.com/illmade-knight/go-dataflow-service/dataflow/devflow/EnrichedTestPayload
                  schema_import_path: ""
                  clustering_fields:
                    - device_id
    servicedirector-bq-flow-infra:
        name: servicedirector-bq-flow-infra
        description: Auto-generated infrastructure resources for the ServiceDirector (servicedirector-bq-flow).
        resources:
            topics:
                - name: command-topic
                - name: completion-topic
                  producer_service:
                    name: servicedirector-bq-flow
                    lookup:
                        key: completion-topic-id
                        method: yaml
            subscriptions:
                - name: command-topic-sub
                  topic: command-topic
                  consumer_service:
                    name: servicedirector-bq-flow
                    lookup:
                        key: command-subscription-id
                        method: yaml
        lifecycle:
            strategy: permanent
deployment_environments: {}
