# services.yaml
name: "ice-dataflow"
region: "europe-west2"

# service_manager_spec describes the ServiceDirector service itself.
service_manager_spec:
  name: "servicedirector-enrichment-flow"
  service_account: "servicedirector-ice-sa"
  deployment:
    source_path: "."
    buildable_module_path: "cmd/bq-servicedirector"

  # REFACTOR: These sections are now required. The hydration logic uses them
  # to auto-generate the Director's Pub/Sub topics and subscriptions.
  command_topic:
    name: "command-topic"
    lookup:
      key: "command-subscription-id"
      method: "yaml"
  completion_topic:
    name: "completion-topic"
    lookup:
      key: "completion-topic-id"
      method: "yaml"

# dataflows describes one or more independent data processing pipelines.
dataflows:
  icestore-flow:
    # services lists the application microservices to be deployed.
    services:
      ingestion-service:
        name: "ingestion-service"
        service_account: "ingestion-sa"
        dependencies:
          - "servicedirector-enrichment-flow"
        deployment:
          source_path: "."
          buildable_module_path: "cmd/ingestion" # Path to your ingestion service code
          secret_environment_vars:
            - name: "MQTT_PASSWORD"
              value_from: "SERVICE_PASS" # The name of the secret in Secret Manager
          environment_vars:
            MQTT_BROKER_URL: "tcp://10.154.0.5:1883"
            MQTT_USERNAME: "sreceiver"
            MQTT_TOPIC: "devices/+/data"
            MQTT_CLIENT_ID: "test-client-devflow"

      enrichment-service:
        name: "enrichment-service"
        service_account: "enrichment-sa"
        dependencies:
          - "servicedirector-enrichment-flow"
        deployment:
          source_path: "."
          buildable_module_path: "cmd/enrichment" # Path to the Enrichment service code

    # Service director will create the following infrastructure before deploying the services.
    resources:
      topics:
        - name: "ingestion-bq"
          producer_service:
            name: "ingestion-service"
        - name: "enrichment-out"
          producer_service:
            name: "enrichment-service"
      subscriptions:
        - name: "bq-ingestion"
          topic: "ingestion-bq"
          consumer_service:
            name: "enrichment-service"
      firestore_databases:
        - name: "(default)"
          consumers:
            - name: "enrichment-service"
      firestore_collections:
        - name: "devices"
          database: "(default)"
          consumers:
            - name: "enrichment-service"