# services.yaml
name: "ice-dataflow"
region: "europe-west2"

# service_manager_spec describes the ServiceDirector service itself.
# The Conductor will deploy this service first.
service_manager_spec:
  name: "servicedirector-ice-flow"
  service_account: "servicedirector-ice-sa"
  deployment:
    source_path: "."
    buildable_module_path: "cmd/bq-servicedirector"

    environment_vars:
      # These topics are used for communication between the Conductor and the Director.
      PROJECT_ID: "replaced-during-hydration"
      SD_COMMAND_TOPIC: "director-commands-bq"
      SD_COMPLETION_TOPIC: "director-events-bq"
      SD_COMMAND_SUBSCRIPTION: "director-command-sub-bq"

# dataflows describes one or more independent data processing pipelines.
dataflows:
  icestore-flow:
    # services lists the application microservices to be deployed.
    services:
      ingestion-service:
        name: "ingestion-service"
        service_account: "ingestion-sa"
        dependencies:
          - "servicedirector-ice-flow"
        deployment:
          source_path: "."
          buildable_module_path: "cmd/ingestion" # Path to your ingestion service code
          secret_environment_vars:
            - name: "MQTT_PASSWORD"
              value_from: "SERVICE_PASS" # The name of the secret in Secret Manager
          environment_vars:
            MQTT_BROKER_URL: "tcp://10.154.0.5:1883"
            MQTT_USERNAME: "sreceiver"
            MQTT_TOPIC: "devices/+/data"
            MQTT_CLIENT_ID: "test-client-devflow"

      icestore-service:
        name: "icestore-service"
        service_account: "icestore-sa"
        dependencies:
          - "servicedirector-ice-flow"
        deployment:
          source_path: "."
          buildable_module_path: "cmd/icestore" # Path to the Icestore service code

    # Service director will create the following infrastructure before deploying the services.
    resources:
      topics:
        - name: "ingestion-bq"
          producer_service:
            name: "ingestion-service"
      subscriptions:
        - name: "bq-ingestion"
          topic: "ingestion-bq"
          consumer_service:
            name: "icestore-service"
      gcs_buckets:
        - name: "iot_data_bk"
          producers:
            - name: "icestore-service"
